version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings: # please keep this alphabetized
    gci:
      skip-generated: true
      custom-order: true
      sections:
        - standard
        - default
        - prefix(go.etcd.io)
    goimports:
      local-prefixes: go.etcd.io
issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usetesting

linters-settings:
  revive:
    rules:
      - name: comment-spacings
  gocyclo:
    min-complexity: 35
