resources:
  - ../default

patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: controller-manager
  - path: patch-manager-flags.yaml
    target:
      kind: Deployment
      name: controller-manager
