# permissions for end users to view etcdrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: etcd-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdrestore-viewer-role
rules:
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdrestores/status
  verbs:
  - get
