{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-operator.fullname" . }}
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "etcd-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "etcd-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etcd-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ include "etcd-operator.image" . }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.controller.leaderElection }}
            - --leader-elect
            {{- end }}
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:{{ .Values.metrics.port }}
            {{- if not .Values.metrics.secure }}
            - --metrics-secure=false
            {{- end }}
            {{- with .Values.controller.watchNamespace }}
            - --watch-namespace={{ . }}
            {{- end }}
          env:
            - name: OPERATOR_IMAGE
              value: {{ .Values.controller.operatorImage | default (include "etcd-operator.image" .) }}
            {{- with .Values.controller.watchNamespace }}
            - name: WATCH_NAMESPACE
              value: {{ . | quote }}
            {{- end }}
            {{- if .Values.controller.restrictClusterIssuer }}
            - name: RESTRICT_CLUSTER_ISSUER
              value: "true"
            {{- end }}
            {{- if not .Values.webhook.enabled }}
            - name: ENABLE_WEBHOOKS
              value: "false"
            {{- end }}
          {{- if .Values.webhook.enabled }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          {{- if .Values.webhook.enabled }}
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: webhook-certs
              readOnly: true
          {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "etcd-operator.fullname" . }}-webhook-server-cert
      {{- end }}
{{- end }}
