# permissions for end users to edit etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: {{ include "etcd-operator.name" . }}-editor-role
rules:
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdclusters/status
  verbs:
  - get
