# permissions for end users to view etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "etcd-operator.labels" . | nindent 4 }}
  name: etcdcluster-viewer-role
rules:
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.etcd.io
  resources:
  - etcdclusters/status
  verbs:
  - get
