apiVersion: v2
name: etcd-operator
description: The official Kubernetes operator for etcd.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# Same value as in values.yml#image.tag

icon: https://avatars.githubusercontent.com/u/41972792?s=48&v=4

home: https://github.com/etcd-io/etcd-operator/tree/main
sources:
  - https://github.com/etcd-io/etcd-operator/helm

maintainers:
  - name: etcd-io

appVersion: v0.1.0
version: 0.1.0
