name: Lint

on:
  push:
  pull_request:

jobs:
  golangci-lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
        with:
          go-version-file: 'go.mod'

      - name: Install golangci-lint
        run: |
          make golangci-lint

      - name: Run golangci-lint
        run: |
          make lint
